language: node_js
services:
  - docker
node_js:
  - 9.2.0
cache:
  directories:
    - node_modules
env:
  - NODE_ENV=production
before_install:
  - npm i -g npm@5.6
install:
  - npm install --dev
script:
  - npm run test
  - npm run build
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo "The bot has already been built so we no longer need the devDependencies";
      npm prune --production;
      export REPO=martijnhols/wowanalyzerdiscordbot;
      export BRANCH=$(
        if [ "$TRAVIS_BRANCH" == "master" ]; then
          echo "latest";
        else
          echo $TRAVIS_BRANCH;
        fi | sed -r 's/\//-/g'
      );
      echo "#docker build";
      docker build --tag $REPO:$BRANCH --file Dockerfile .;
      echo "#docker login";
      docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD";
      echo "#docker push";
      docker push $REPO:$BRANCH;
    fi
