name: 'Build'

on: [push, pull_request]

env:
  CI: true
  DOCKER_BUILD_TAG: build-${{ github.run_number }}

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    env:
      YARN_CACHE_FOLDER: .yarn-cache
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - run: yarn install
      - run: yarn run test
      - run: yarn run build
      - run: yarn install --production --ignore-scripts --prefer-offline # yarn prune is annoyingly a no-op
      - run: docker build --tag discordbot .
      - run: bash .github/workflows/deploy.sh
        if: github.event_name != 'pull_request' && github.repository == 'wowanalyzer/discordbot'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
